### ISSUE TITLE
Handle/keep scroll during navigation

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#285] opened 2016-03-10 12:28 UTC
I don't know if this is a normal behaviour but when navigating around, the scroll bar is as the previous page position.

**Comment by MoOx** [comment] 2016-03-11 05:37
Yeah we should offer something to automatically scroll at the top (smoothly?)

**Comment by thangngoc89** [comment] 2016-03-11 05:41
I thought this should be handled automatically be react-router

**Comment by MoOx** [comment] 2016-03-11 05:42
Where did you see that?
I don't see why, it's an "opinionated" behavior.

**Comment by thangngoc89** [comment] 2016-03-11 05:43
I don't remember where. Anyway, this should be in LayoutContainer right? user can remove it easily

**Comment by MoOx** [comment] 2016-03-11 05:44
We sould provide this options:

- direct scroll at top (true)
- smooth scroll at top (integer, ms)
- no scroll (false)
- custom callback (fn)

**Comment by thangngoc89** [comment] 2016-03-11 05:46
Changed status.

**Comment by thangngoc89** [comment] 2016-04-21 18:32
This is actually very easy to do. There is a packages desinged for this job.

https://github.com/taion/scroll-behavior/blob/master/README.md

**Comment by MoOx** [comment] 2016-04-30 11:31
https://github.com/ryanflorence/react-router-restore-scroll

Plan is to integrate this in react-router itself.

**Comment by ben-eb** [comment] 2016-05-02 15:20
Here's what worked for me (thanks @thangngoc89 & @kuzvac):

```js
import React, {Component, PropTypes} from "react";
import {Route} from "react-router";
import PhenomicPageContainer from "phenomic/lib/PageContainer";
import LayoutContainer from "../LayoutContainer";
import * as layouts from '../layouts';

class PageContainer extends Component {
    static propTypes = {
        params: PropTypes.object.isRequired,
    };

    render () {
        const {props} = this;
        return (
            <PhenomicPageContainer
                {...props}
                layouts={layouts}
            />
        );
    }
    
    componentWillReceiveProps (props) {
        if (props.params.splat !== this.props.params.splat && !window.location.hash) {
            window.scrollTo(0, 0);
        }
    }
    
    componentDidMount () {
        window.addEventListener('hashchange', this.scrollToAnchor);
        this.scrollToAnchor();
    }
    
    scrollToAnchor () {
        const hashParts = window.decodeURIComponent(window.location.hash).split('#');
        if (hashParts.length === 2) {
            const hash = hashParts.slice(-1)[0];
            document.querySelector(`[id="${hash}"]`).scrollIntoView();
        }
    }
}

export default (
  <Route component={LayoutContainer}>
    <Route
        path="*"
        component={PageContainer}
    />
  </Route>
);
```

**Comment by thangngoc89** [comment] 2016-05-02 15:54
@ben-eb Why do you need to listen to `hashchange` event ? Phenomic doesn't overide default behaviour.

**Comment by ben-eb** [comment] 2016-05-02 16:00
Looks like you only need that if you are using the hash history, which Phenomic doesn't do. Nevermind, removed. 👍

**Comment by MoOx** [comment] 2016-05-02 19:33
So I guess that `componentWillReceiveProps`  code is only necessary?

**Comment by ben-eb** [comment] 2016-05-02 20:09
@MoOx Yes :+1:

**Comment by MoOx** [comment] 2016-05-03 20:35
FYI https://twitter.com/MoOx/status/727595667674255360

**Comment by taion** [comment] 2016-05-03 20:40
cc @ryanflorence

As it stands right now, both scroll-behavior and react-router-scroll expose a `shouldUpdateScroll` callback to control specific behavior, see e.g. https://github.com/taion/react-router-scroll#custom-scroll-behavior.

They do not currently have support for scrollable divs like react-router-restore-scroll, but I think the support for actually scrolling the window in the face of adversity (i.e. browsers) is more battle-tested.

Ideally we combine everything in one library that has the best of both.

**Comment by MoOx** [comment] 2016-06-10 12:26
Nice solution seems to be implemented in react-boilerplate https://github.com/mxstbr/react-boilerplate/blob/229f39e3cd09a555e16da0e9d21ea4bd3a17b840/app/app.js#L66-L80
Tagging as bug, as it's pretty annoying.

**Comment by taion** [comment] 2016-06-10 14:29
I'm confused by what the check there does. If I'm reading it correctly, it seems to scroll to the top on every page transition, even when that transition is e.g. a `POP`. I'm not sure why that's correct.

**Comment by taion** [comment] 2016-06-10 14:29
cc @mxstbr

**Comment by mxstbr** [comment] 2016-06-10 15:10
Uhh, I'm not sure about the terminology here, what is a `POP` transition?

**Comment by taion** [comment] 2016-06-10 15:11
`POP` = when you hit the back button or something

By default react-router-scroll should scroll you to the top of a page whenever you e.g. click on a link or something, but restore the old scroll position if pathname changes because you hit the back button.

**Comment by mxstbr** [comment] 2016-06-10 15:12
I guess that makes sense, hadn't thought about that at all tbh! The solution we have is only in there because it's annoying when you're editing the footer and HMR kicks in and scrolls back to the top.

Would appreciate an improvement!

**Comment by mxstbr** [comment] 2016-06-10 15:55
No, but it will prevent a jump to `[0, 0]`. I.e. we want to go to the top of the page when a new one is opened, but do the default stuff when that's not the case.

**Comment by taion** [comment] 2016-06-10 15:59
That's supposed to be what you get if you just do `useScroll()` without a custom `shouldUpdateScroll` at all, though, isn't it?

**Comment by mxstbr** [comment] 2016-06-10 16:26
I don't know, you made the library! I don't remember why we put it in, if that's the case I'd love to remove those lines of code!

**Comment by taion** [comment] 2016-06-10 17:39
Okay – when you have a chance, then, could you let me know what happens if you take out that callback? I believe everything should work as you expect without it.

**Comment by mxstbr** [comment] 2016-06-11 10:26
It does indeed, thanks @taion! Fixed in mxstbr/react-boilerplate@15006efb6079194805d0528f9b48f3579fe85ccf, works as expected.

**Comment by MoOx** [comment] 2016-06-11 10:34
Cool, I will implement this asap then!
Thank you both of you!

**Comment by taion** [comment] 2016-06-11 17:11
Glad to hear that. The idea was that most use cases could be satisfied by just the one-liner.

Unfortunately I've had almost no time to work on front-end lately to work on fleshing out functionality and adding this to the router, but this solution should work for now.

**Closed** 2016-06-12 04:40 UTC
Labels: type: bug

**Comment by MoOx** [comment] 2016-06-12 08:46
@taion since I implemented this, a `<Link to="/">` gives errors ``SecurityError: The operation is insecure.`` @thangngoc89 is having the issue as well. Any idea?

**Comment by thangngoc89** [comment] 2016-06-12 08:50
Full error message (on Chrome)

> Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:8080' and URL 'http://localhost:8080/tim-hieu-dinh-dang-mdict/'.

**Comment by taion** [comment] 2016-06-12 15:08
This is specifically a regression from the scroll thing? That's really weird – I don't do anything to affect how push/replace work.

**Comment by thangngoc89** [comment] 2016-06-12 15:25
@taion it was fixed here https://github.com/MoOx/phenomic/commit/c6a7164fd083b2f1b1561dd3fe9211556ba5fcc5

**Comment by taion** [comment] 2016-06-12 15:43
Ugh we still have bugs with trailing slash in `basename`? We should fix those...

**Comment by taion** [comment] 2016-06-12 15:47
That workaround shouldn't be necessary. How can I reproduce the error?

**Comment by thangngoc89** [comment] 2016-06-12 15:51
@taion thanks for looking to this. 

For reproducing, you can : 

- Clone this https://github.com/MoOx/phenomic/commit/1e6d472eb1c00fed83f1c2e8431ad274468cf6fa

```
npm install
npm run docs-start
```

Navigate to a different page and then click on the Phenomic logo on Header bar (to return to home page)

**Comment by MoOx** [comment] 2016-06-12 17:09
Also posted full instruction in https://github.com/reactjs/react-router/issues/3184#issuecomment-225448418
