### ISSUE TITLE
HMR not being called on Windows

### ISSUE THREAD

**Issue by facelesspanda** [MoOx/phenomic#779] opened 2016-09-24 13:37 UTC
My browser is Chrome, stable version `53.0.2785.116 (Official Build) m (64-bit)` as of now.
OS: Windows 10, latest version (there were even updates this night... I hate the new auto-auto-updates D: )

I wanted to try out Phenomic, so I simply followed the setup guide.

went to a new empty folder, ran these in order and did nothing else:

```
npm i phenomic
```

```
./node_modules/.bin/phenomic setup
```

```
npm install
```

```
npm start
```

My browser page opened, with a stylized list of links to the docs and some posts that are in the boilerplate, so I thought "cool it works"

But then I started editing `content/index.md`, and I noticed nothing was output to the terminal, and no change was reflected in my browser — the dev console also didn't budge.

In small words: no HMR hot loading on windows 10 with the default config.
It must be an upstream issue, but still, it's cool to know here too.

**Comment by facelesspanda** [comment] 2016-09-24 13:53
Update:
It HMR reloads when my project is not in a path containing any type of brackets, or spaces.
It's a path issue somewhere upstream. Most likely chokidar.

**Comment by thangngoc89** [comment] 2016-09-24 18:07
Which page are you seeing the posts? Currently, hmr for markdown content only works on pages that contains 1 markdown posts, not the one with mutiple posts, which is filtered with enhanceCollection

**Comment by facelesspanda** [comment] 2016-09-24 21:32
I'm not sure I understand the question, but it was the boilerplate's homepage index.html file, at the root of the content tree. Though its layout contained a list of posts, its markdown content was updated correctly once my path was free of spaces or brackets. Editing the homepage index.js layout updated the page too. Didn't try editing the title of one of the posts from its own file.

**Comment by thangngoc89** [comment] 2016-09-25 03:04
I see. I guess this is something we can improve. I use Windows 10 too but I never name a file with spaces or brackets.

**Comment by facelesspanda** [comment] 2016-09-25 11:43
I have a folder structure where "categories" (like "development", "movies", "programs"...) are named in brackets to appear before any other folder when I sort by name. Never had problems before dealing with CLI tools, because a lot of gui software manage those by simply using the OS's file system management. Here, there are a lot of string manipulation directly between tools like Chokidar or Path, so it's easy to just not know who does what with there paths.

**Comment by evenkiel** [comment] 2017-02-27 12:44
The PR for #943 resolved the issue. Additionally, there was another solution posted by someone else on that same thread. Hot reloads worked fine for me for all md files after the fix. Please consider applying the fixes from the closed item to address this earlier opened issue.

FWIW, the path I was using had no spaces or special characters.

**Comment by MoOx** [comment] 2017-02-27 12:50
Can anyone confirm which solution works/is the best?

**Comment by pcguru** [comment] 2017-03-20 20:16
I'm seeing the same problem. Editing text in index.md gives this error in the console on the second change (the first one works):

(btw love phenomic so far)

```
[HMR] Cannot check for update (Full reload needed)
handleError @ process-update.js?e13e:115
applyCallback @ process-update.js?e13e:45
hotApply @ phenomic.browser.454c1e3….js:528
cb @ process-update.js?e13e:52
hotUpdateDownloaded @ phenomic.browser.454c1e3….js:312
hotAddUpdateChunk @ phenomic.browser.454c1e3….js:284
webpackHotUpdateCallback @ phenomic.browser.454c1e3….js:5
(anonymous) @ 0.454c1e3….hot-update.js:1
process-update.js?e13e:116 [HMR] TypeError: Cannot read property '__dataUrl' of undefined
    at eval (eval at <anonymous> (http://localhost:3333/phenomic.browser.454c1e338f7ff0ca0dbf.js:2838:2), <anonymous>:19:25)
```

`reload` in the function `performReload` is always false, so a full reload is not performed either. A missing arg somewhere?

```javascript
function performReload() {
    if (reload) {
      if (options.warn) console.warn("[HMR] Reloading page");
      window.location.reload();
    }
  }
```

**Comment by MoOx** [comment] 2017-03-23 05:49
What is your OS?

**Comment by micnigh** [comment] 2017-04-10 03:44
I ran into the same issue, so I looked into it a bit.  The patch works, but does not address the cause of the problem.  It looks like collection filenames are having their slash directions set incorrectly on windows, which causes the find item test in `src/client/hot-md.js` to fail.

https://github.com/MoOx/phenomic/blob/master/src/client/hot-md.js#L6

![image](https://cloud.githubusercontent.com/assets/1274048/24843247/d4ab725c-1d55-11e7-9569-e14b42768891.png)

The `__filename` path seems to be set on https://github.com/MoOx/phenomic/blob/master/src/loader/index.js#L42

One simple solution might be to replace "\\" with "/" on the relativePath variable.

**Comment by MoOx** [comment] 2017-04-10 13:02
@micnigh mind doing a PR?

**Closed** 2017-04-18 05:58 UTC
Labels: status: needs investigation
