### ISSUE TITLE
fresh boilerplate shows 404 page

### ISSUE THREAD

**Issue by inventanew** [MoOx/phenomic#589] opened 2016-08-01 17:45 UTC
fresh boilerplate shows 404 page. How do I default to the home page. None of the page routes are working.

**Comment by MoOx** [comment] 2016-08-01 21:29
It seems related to this https://github.com/wooorm/unified/issues/7

**Comment by MoOx** [comment] 2016-08-02 04:28
A fix is pending. This will be fixed when a new release of `unified` will be cut, hopefully pretty quickly.

**Comment by MoOx** [comment] 2016-08-02 07:19
Should be good. Just reinstall and you should have the patch.

**Comment by inventanew** [comment] 2016-08-03 01:10
you are awesome thanks a million!

**Comment by akfish** [comment] 2016-08-27 00:57
I'm having the same problem with latest version 0.16.2 on both Windows 10 x64+node 6.4.0 and Ubuntu 14.04+node 4.4.7

`npm start` gave some warning on windows:
```
PS F:\dev\phenomic\foo> npm start

> foo@ start F:\dev\phenomic\foo
> phenomic start

  phenomic:builder:server Dev server started on http://0.0.0.0:3333/ +0ms
webpack built cb5f2d699c406fdda1c0 in 10574ms
  phenomic:builder:server Webpack compilation done +10s
Hash: cb5f2d699c406fdda1c0
Version: webpack 1.13.2
Time: 10574ms
                                                             Asset       Size  Chunks             Chunk Names
                    404.html.f3d82a4d938b593823c37ead979b3b86.json  343 bytes          [emitted]
                                                          feed.xml    1.07 kB          [emitted]
                  index.html.29ac6c7c776d292060e9edca0f868180.json  835 bytes          [emitted]
          loading/index.html.4f959959ceecdafbb30e2e8fd2869cdc.json  506 bytes          [emitted]
 posts/first-post/index.html.4a5613b2efb7336faddeb36e490da773.json  356 bytes          [emitted]
posts/hello-world/index.html.71dba0e386497410490147d8e028e650.json  394 bytes          [emitted]
                          phenomic.browser.cb5f2d699c406fdda1c0.js    6.97 MB       0  [emitted]  phenomic.browser
chunk    {0} phenomic.browser.cb5f2d699c406fdda1c0.js (phenomic.browser) 2.52 MB [rendered]
    [0] multi phenomic.browser 40 bytes {0} [built]
    [1] ./~/react/react.js 56 bytes {0} [built]
    [2] ./~/fbjs/lib/invariant.js 1.49 kB {0} [built]
    [3] ./~/fbjs/lib/warning.js 2.1 kB {0} [built]
    [4] ./~/react/lib/reactProdInvariant.js 1.27 kB {0} [built]
    [5] ./~/object-assign/index.js 1.99 kB {0} [built]
// REMOVED
  [743] ./~/vfile-location/index.js 2.81 kB {0} [built]
  [744] ./~/vfile/index.js 14.8 kB {0} [built]
  [745] ./~/whatwg-fetch/fetch.js 10.4 kB {0} [built]
  [746] ./~/wrappy/wrappy.js 905 bytes {0} [built]

WARNING in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
And thrown some errors on Ubuntu:
```
vagrant@vagrant-ubuntu-trusty-64:~/foo$ npm start

> foo@ start /home/vagrant/foo
> phenomic start

  phenomic:builder:server Dev server started on http://0.0.0.0:3333/ +0ms
webpack built e06289a5a95d5f336a6d in 30692ms
  phenomic:builder:server Webpack compilation done +31s
Hash: e06289a5a95d5f336a6d
Version: webpack 1.13.2
Time: 30692ms
                                                             Asset       Size  Chunks       Chunk Names
                    404.html.f3d82a4d938b593823c37ead979b3b86.json  343 bytes
                                                          feed.xml    1.07 kB
                  index.html.69be905ce2a7b9af56b79d96909e0b87.json  835 bytes
          loading/index.html.4f959959ceecdafbb30e2e8fd2869cdc.json  506 bytes
 posts/first-post/index.html.4a5613b2efb7336faddeb36e490da773.json  355 bytes
posts/hello-world/index.html.71dba0e386497410490147d8e028e650.json  393 bytes
                          phenomic.browser.e06289a5a95d5f336a6d.js    6.95 MB       0       phenomic.browser
chunk    {0} phenomic.browser.e06289a5a95d5f336a6d.js (phenomic.browser) 2.51 MB [rendered]
    [0] multi phenomic.browser 40 bytes {0} [built]
    [1] ./~/react/react.js 56 bytes {0} [built]
    [2] ./~/fbjs/lib/invariant.js 1.49 kB {0} [built]
    [3] ./~/fbjs/lib/warning.js 2.1 kB {0} [built]
    [4] ./~/react/lib/reactProdInvariant.js 1.27 kB {0} [built]
    [5] ./~/object-assign/index.js 1.99 kB {0} [built]
// REMOVED
  [740] (webpack)-hot-middleware/client-overlay.js 1.74 kB {0} [built]
  [741] (webpack)-hot-middleware/client.js 4.49 kB {0} [built]
  [742] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
  [743] ./~/whatwg-fetch/fetch.js 10.4 kB {0} [built]
  [744] ./~/wrappy/wrappy.js 905 bytes {0} [built]

ERROR in ./~/css-loader!./~/postcss-loader!./web_modules/LayoutContainer/index.global.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
 @ ./web_modules/LayoutContainer/index.global.css 4:14-131 13:2-17:4 14:20-137

ERROR in ./~/css-loader?modules&localIdentName=[path][name]--[local]--[hash:base64:5]!./~/postcss-loader!./web_modules/l
ayouts/PageError/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
 @ ./web_modules/layouts/PageError/index.css 4:14-192 13:2-17:4 14:20-198

ERROR in ./~/css-loader?modules&localIdentName=[path][name]--[local]--[hash:base64:5]!./~/postcss-loader!./web_modules/L
ayoutContainer/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
 @ ./web_modules/LayoutContainer/index.css 4:14-186 13:2-17:4 14:20-192

ERROR in ./~/css-loader?modules&localIdentName=[path][name]--[local]--[hash:base64:5]!./~/postcss-loader!./web_modules/l
ayouts/PageLoading/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
 @ ./web_modules/layouts/PageLoading/index.css 4:14-192 13:2-17:4 14:20-198

ERROR in ./~/css-loader?modules&localIdentName=[path][name]--[local]--[hash:base64:5]!./~/postcss-loader!./web_modules/F
ooter/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
 @ ./web_modules/Footer/index.css 4:14-186 13:2-17:4 14:20-192

ERROR in ./~/css-loader?modules&localIdentName=[path][name]--[local]--[hash:base64:5]!./~/postcss-loader!./web_modules/H
eader/index.css
Module build failed: Error: Cannot find module '../features'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/foo/node_modules/caniuse-api/dist/index.js:19:32)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/foo/node_modules/babel-register/lib/node.j
s:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Opened in Chrome:
![image](https://cloud.githubusercontent.com/assets/922715/18023940/aecf120c-6c32-11e6-9c3e-b6e37c53805c.png)

![image](https://cloud.githubusercontent.com/assets/922715/18023994/731b8afa-6c33-11e6-9a7c-a622f4113505.png)

`npm run build` on Windows gave no erros. But no `index.html`s were generated:
```
PS F:\dev\phenomic\foo> npm run build

> foo@ build F:\dev\phenomic\foo
> phenomic build

  phenomic:builder ✓ Static build: assets copy completed +0ms
  phenomic:builder ✓ Static build: client build completed +55s
  phenomic:builder ✓ Static build: static build completed +26s
PS F:\dev\phenomic\foo> ls .\dist\


    Directory: F:\dev\phenomic\foo\dist


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/27/2016   8:52 AM                assets
d-----        8/27/2016   8:53 AM                loading
d-----        8/27/2016   8:53 AM                posts
-a----        8/27/2016   8:53 AM              0 .nojekyll
-a----        8/27/2016   8:53 AM            343 404.html.f3d82a4d938b593823c37ead979b3b86.json
-a----        8/27/2016   8:53 AM           1073 feed.xml
-a----        8/27/2016   8:53 AM            839 index.html.29ac6c7c776d292060e9edca0f868180.json
-a----        8/27/2016   8:53 AM           2189 phenomic.browser.1c1796bb1d2093d9323e.css
-a----        8/27/2016   8:53 AM         933753 phenomic.browser.1c1796bb1d2093d9323e.js
```

On Unbuntu, it exited with error:
```
vagrant@vagrant-ubuntu-trusty-64:~/foo$ npm run build

> foo@ build /home/vagrant/foo
> phenomic build

  phenomic:builder ✓ Static build: assets copy completed +0ms
Killed

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! foo@ build: `phenomic build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the foo@ build script 'phenomic build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     phenomic build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/foo/npm-debug.log
```

**Comment by akfish** [comment] 2016-08-27 01:15
Strangely, it works without any issue in `cmd.exe`. I guess it just doesn't like neither powershell nor vagrant ssh.

**Comment by thangngoc89** [comment] 2016-08-27 07:11
I got this one yesterday too 

```
Module build failed: Error: Cannot find module '../features'
```

`rm -rf node_modules && npm install` solved it.

**Comment by MoOx** [comment] 2016-08-27 21:40
Weird that this happens in different envs... Any specific idea that can be the source of the error @akfish ? I am not really used to cmd/powershell etc... (macos user).

**Comment by akfish** [comment] 2016-08-28 01:04
@MoOx The main difference in powershell is the following warnings:

```
WARNING in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
 
So I did some digging. It seems to be related to webpack/webpack#2362.
Node's builtin functions are not consistent when handling drive letters in the file path. In powershell it's always in uppercase (e.g. `F://dev`) and in cmd.exe it's the opposite (e.g. `f://dev').

But I'm not sure if this could break phonemic since it's *just a warning*.

**Comment by MoOx** [comment] 2016-08-30 07:20
Yeah this is kind of weird...

**Comment by MoOx** [comment] 2016-11-03 08:06
@akfish do you still have the issue?

**Comment by akfish** [comment] 2016-11-04 02:15
The issue is still present in PowerShell with latest version(`"phenomic": "^0.18.0"`), but the error messages are diffrent:
```
PS F:\dev\test> npm start

> foo-bar@ start F:\dev\test
> phenomic start

i Phenomic is starting +0.27s
√ Development server listening on http://0.0.0.0:3333/ +2.11s
× Updated with warnings

‼ Warning in ./content/index.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added
automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more informat
ion, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (.\node_modules\phenomic\lib\loader\index.js:88:11)
 @ ./content \.(md|markdown)$

‼ Warning in ./content/404.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added
automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more informat
ion, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (.\node_modules\phenomic\lib\loader\index.js:88:11)
 @ ./content \.(md|markdown)$

‼ Warning in ./content/posts/hello-world.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added
automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more informat
ion, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (.\node_modules\phenomic\lib\loader\index.js:88:11)
 @ ./content \.(md|markdown)$

‼ Warning in ./content/posts/first-post.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added
automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more informat
ion, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (.\node_modules\phenomic\lib\loader\index.js:88:11)
 @ ./content \.(md|markdown)$

‼ Warning in (webpack)/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

‼ Warning in ./~/webpack/buildin/module.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

It works find in `cmd.exe`.

**Comment by akfish** [comment] 2016-11-04 03:36
It works in vagrant ssh now.

**Comment by MoOx** [comment] 2016-11-04 07:15
This is very weird to get this warnings. PowerShell is weird. I don't have time to investigate on this at the moment. Let me open a new issue about that.

https://github.com/MoOx/phenomic/issues/865

**Closed by MoOx** 2016-11-04 07:15 UTC
Labels: type: bug
